name=str(input("qual e seu nome"))
neymar=len (name)
if neymar >=3:
    idade=int(input("qual a sua idade neymar"))
if idade>0 and idade<150 :
    salario=int(input("qual o salario do ney"))
if salario>0:
    sexo=str(input("seu sexo e neymar ou neymara?"))
if sexo=="neymar" or "neymara":
    estado=str(input("digite o seu estado civil solteiro,casado,viuvo,divorciado :"))
if estado=="solteiro"or"casado"or"viuvo"or"divorciado":
    print("neymar esta dentro da copaaa batendo na croacia e eles ficaram calados")
else:
    print("neymar esta fora da copa apanho pra argentina na final")
